/* ============================================================
   Souz-M Laboratory — UX case copy, EN / RU.

   Merges into window.I18N like case-chistetika.js, so main.js
   resolves these keys like any other. The English strings are
   also the fallback text in case-souzm.html, so the page reads
   correctly before this file loads.

   Key prefixes
     sm.head.*   header and meta
     sm.sN.*     section N, in page order (captions and alt text
                 of the figures in that section included)
   ============================================================ */

(function () {
  const EN = {
    "sm.doc.title": "Souz-M Laboratory — UX case — Dmitrii Andreenko",
    "sm.back": "All work",
    "sm.k.role": "Role",
    "sm.k.team": "Team",
    "sm.k.year": "Year",
    "sm.k.live": "Live",
    "sm.next": "Next case — Chistetika Lab",
    "sm.head.01": "UX Case · 2025",
    "sm.head.02": "Souz-M Laboratory",
    "sm.head.03": "Making a hidden lab a selling point",
    "sm.head.04": "Lead editor — research, information architecture, UX writing, wireframes",
    "sm.head.05": "Shulman_prod (creative direction, visual design)",
    "sm.head.06": "2025",
    "sm.s1.01": "The brief",
    "sm.s1.02": "The ask: a page to host a PDF.",
    "sm.s1.03": "Souz-M sells upholstery fabrics. Every fabric from Souz-M and its sister brand Chistetika is tested in the company’s own accredited laboratory. The specifications on product pages aren’t copied from suppliers — they’re measured.",
    "sm.s1.04": "That was one of the brand’s strongest competitive advantages, and it wasn’t communicated anywhere.",
    "sm.s1.05": "The task was a landing page for a new laboratory guide. I proposed a page that sells the lab itself and uses the guide as its depth.",
    "sm.s1.06": "The released Souz-M laboratory page: a hero with video of a testing machine and a button to download the full guide as a PDF",
    "sm.s1.07": "The page",
    "sm.s1.08": "A lab most buyers never knew existed",
    "sm.s2.01": "The problem",
    "sm.s2.02": "The proof spoke the language of the laboratory.",
    "sm.s2.03": "“Martindale abrasion test” means little to someone choosing fabric for furniture.",
    "sm.s2.04": "Numbers without interpretation are useless.",
    "sm.s2.05": "Is 30,000 cycles a lot or a little? Without a reference point, the number does no work.",
    "sm.s2.06": "A laboratory is a process, not a product.",
    "sm.s2.07": "You can’t put it in a cart. The page had to make invisible work visible.",
    "sm.s2.08": "What the lab measures",
    "sm.s2.09": "Martindale abrasion test — <span class=\"dg__fig\">30,000</span> cycles",
    "sm.s2.10": "What the buyer asks",
    "sm.s2.11": "Will it wear through on a sofa?",
    "sm.s2.12": "What the page has to do",
    "sm.s2.13": "Connect the two.",
    "sm.s3.01": "Starting point",
    "sm.s3.02": "The starting material was a technical description of the testing process: methods, standards and units of measurement. I rewrote it as a guide for a non-specialist reader, and Shulman_prod designed it as a 20-page PDF.",
    "sm.s3.03": "The first version of the page moved that content into the website template: a headline, a definition and a list of seven parameters.",
    "sm.s3.04": "Everything was correct. Nothing worked.",
    "sm.s3.05": "The list answered a question the visitor hadn’t asked.",
    "sm.s3.06": "<strong>Who the page is for.</strong> People choosing fabric for furniture. My working hypothesis was that none of them ask about tests. They ask whether a fabric will hold its shape, fade or wear through. It stayed a hypothesis, and the structure was built on it.",
    "sm.s3.07": "The guide — page 3 of 20",
    "sm.s3.08": "Spread 3 of the 20-page guide, headed “What are laboratory tests?”, with icons for each property and a photograph of a testing instrument",
    "sm.s3.09": "v0 — the same content, poured into a template",
    "sm.s3.10": "The first version of the page: a hero slider of fabric rolls, the question “What are laboratory tests?”, and seven laboratory parameters set as a list in capitals; the empty space between the two parts is cut out",
    "sm.s3.11": "v0",
    "sm.s3.12": "Correct, and useless",
    "sm.s4.01": "Structure",
    "sm.s4.02": "The page doesn’t replace the guide. It sells it.",
    "sm.s4.03": "Each section answers one question.",
    "sm.s4.04": "The six sections of the page and the question each one answers",
    "sm.s4.05": "Hero",
    "sm.s4.06": "What is this? (with an immediate link to the guide)",
    "sm.s4.07": "What determines quality",
    "sm.s4.08": "What do you test, and why should I care?",
    "sm.s4.09": "How testing works",
    "sm.s4.10": "Is this real or just marketing?",
    "sm.s4.11": "Tests on video",
    "sm.s4.12": "Show me.",
    "sm.s4.13": "Parameters and what they mean",
    "sm.s4.14": "How do I read the numbers on a fabric page?",
    "sm.s4.15": "The guide",
    "sm.s4.16": "Where do I get the full story?",
    "sm.s4.17": "Marked: the order was the decision — properties first, proof second, parameters third.",
    "sm.s4.18": "The guide is offered twice: in the hero for visitors who came for it, and at the end for those the page convinced. Every parameter ends with a link to the guide. The page works as an index to the PDF.",
    "sm.s4.19": "Hero",
    "sm.s4.20": "Download",
    "sm.s4.21": "What determines quality",
    "sm.s4.22": "How testing works",
    "sm.s4.23": "Tests on video",
    "sm.s4.24": "Parameters and what they mean",
    "sm.s4.25": "Read more in the guide ×8",
    "sm.s4.26": "The guide",
    "sm.s4.27": "Download",
    "sm.s4.28": "The guide · 20 pages",
    "sm.s4.29": "The index",
    "sm.s4.30": "Two entry points, eight shortcuts",
    "sm.s4.31": "How the structure got there",
    "sm.s4.32": "v0",
    "sm.s4.33": "Full-page export of v0",
    "sm.s4.34": "Guide content in the website template",
    "sm.s4.35": "v1",
    "sm.s4.36": "Full-page export of v1",
    "sm.s4.37": "Properties placed inside the hero; the first two-part parameter card",
    "sm.s4.38": "v2",
    "sm.s4.39": "Full-page export of v2, the version handed over",
    "sm.s4.40": "Properties moved out of the hero into their own section: a first screen should do one job. The version I handed over",
    "sm.s4.41": "v3",
    "sm.s4.42": "Full-page export of v3",
    "sm.s4.43": "Grey wireframes on the brand’s grid",
    "sm.s4.44": "v4",
    "sm.s4.45": "Full-page export of v4",
    "sm.s4.46": "Real laboratory photography",
    "sm.s4.47": "Released",
    "sm.s4.48": "Full-page export of the released page",
    "sm.s4.49": "Visual design by Shulman_prod",
    "sm.s4.50": "Six versions, from template to release.",
    "sm.s5.01": "Decisions",
    "sm.s5.02": "Properties instead of parameters",
    "sm.s5.03": "The laboratory measures eight parameters. Buyers ask about four properties: weight, strength, colourfastness and abrasion resistance.",
    "sm.s5.04": "I grouped the parameters under these properties and made the properties the tabs.",
    "sm.s5.05": "How buyers ask",
    "sm.s5.06": "What the lab measures",
    "sm.s5.07": "Weight",
    "sm.s5.08": "Fabric weight",
    "sm.s5.09": "Thickness",
    "sm.s5.10": "Strength",
    "sm.s5.11": "Breaking force",
    "sm.s5.12": "Elongation at break",
    "sm.s5.13": "Colourfastness",
    "sm.s5.14": "Colourfastness to light",
    "sm.s5.15": "Abrasion resistance",
    "sm.s5.16": "Pilling resistance",
    "sm.s5.17": "Martindale abrasion test",
    "sm.s5.18": "Flex resistance",
    "sm.s5.19": "faux leather",
    "sm.s5.20": "The translation",
    "sm.s5.21": "Four questions, eight answers",
    "sm.s5.22": "The groups follow the buyer’s question, not the lab’s taxonomy. That’s why one tab holds three parameters and another holds one. Flex resistance applies to faux leather rather than fabric, so it went where a buyer would look for it: under wear.",
    "sm.s5.23": "The visitor enters through a familiar word and leaves with the technical term they’ll now recognise on a product page. Everything else on the page depends on this translation.",
    "sm.s5.24": "Two questions for every parameter",
    "sm.s5.25": "Each parameter answers two questions. First: what is it, and how is it measured? Second: what does it mean for furniture?",
    "sm.s5.26": "A number becomes an argument only when its consequence is stated next to it.",
    "sm.s5.27": "<span class=\"dg__fig\">Parameter 3</span> Breaking force",
    "sm.s5.28": "What it is",
    "sm.s5.29": "The maximum force a fabric withstands when stretched until it breaks. Measured in newtons <span class=\"dg__fig\">(N)</span>.",
    "sm.s5.30": "What it means",
    "sm.s5.31": "The higher the breaking force, the stronger the fabric: it withstands tension better, deforms less and holds its seams longer.",
    "sm.s5.32": "Read more in the guide",
    "sm.s5.33": "Anatomy",
    "sm.s5.34": "Definition on the left, consequence on the right",
    "sm.s5.35": "I tested three layouts for the card: vertical, visualised and two-column. In the released design, Shulman_prod turned the two halves into an expandable accordion, so eight parameters don’t become a wall of text.",
    "sm.s5.36": "v1 — vertical",
    "sm.s5.37": "Parameter card exploration v1: a vertical blue card for fabric weight with property chips",
    "sm.s5.38": "v2 — visualised",
    "sm.s5.39": "Parameter card exploration v2: a card with a green visualisation of the fabric surface",
    "sm.s5.40": "v3 — two-column",
    "sm.s5.41": "Parameter card exploration v3: a two-column card with a grey header and a blue interpretation half",
    "sm.s5.42": "The released dark “Parameters and what they mean” section, with the first item expanded",
    "sm.s5.43": "Released",
    "sm.s5.44": "The accordion, by Shulman_prod",
    "sm.s5.45": "Process as proof",
    "sm.s5.46": "Four steps — preparation, testing, documentation, release to market — aren’t there to explain the process. They prove that “tested” means there is a test report behind the claim.",
    "sm.s5.47": "That’s why the test report is named in the page’s opening paragraph.",
    "sm.s5.48": "The four-step process strip from the live page: preparation, testing, documentation, release to market",
    "sm.s5.49": "the proof",
    "sm.s5.50": "Proof",
    "sm.s5.51": "The third step carries the argument",
    "sm.s6.01": "Language",
    "sm.s6.02": "The technical material had to be rewritten without losing accuracy.",
    "sm.s6.03": "“Pilling” stayed, with a plain explanation: small balls of tangled fibre.",
    "sm.s6.04": "Five-point scales got a threshold, so a score means something:",
    "sm.s6.05": "A score below 4 means the material will lose its colour quickly.",
    "sm.s6.06": "The goal wasn’t to remove terminology. It was to make every term interpretable.",
    "sm.s6.07": "v0 · the template",
    "sm.s6.08": "RESISTANCE TO FUZZING AND PILLING",
    "sm.s6.09": "Released · Parameter 6",
    "sm.s6.10": "How well a fabric keeps its surface smooth and resists pilling — small balls of tangled fibre — in use. Rated on a five-point scale. A score below 4 means the material is prone to pilling.",
    "sm.s6.11": "Before / after",
    "sm.s6.12": "Same fact, different reader",
    "sm.s6.13": "Below 4: fades fast.",
    "sm.s7.01": "After handoff",
    "sm.s7.02": "I didn’t create the visual design. The structure, section order and copy went to production unchanged.",
    "sm.s7.03": "Shulman_prod added the visual layer the structure left room for: laboratory photography in the tabs, process icons and a dark parameter section over an interior photograph. That last move takes the conversation from the lab back to the room: from how a fabric is tested to why it matters.",
    "sm.s7.04": "v2 — the version I handed over",
    "sm.s7.05": "The full v2 prototype, the version handed to the design studio",
    "sm.s7.06": "Released — souz-m.ru/laboratoriya",
    "sm.s7.07": "The released page in full, scrolled from top to bottom",
    "sm.s7.08": "Structure unchanged, visual layer added.",
    "sm.s8.01": "Result",
    "sm.s8.02": "The page is live at souz-m.ru/laboratoriya and linked from the site menu and footer.",
    "sm.s8.03": "I don’t have access to the page’s analytics, so there are no numbers here. The result I can show is the one the brief was about.",
    "sm.s8.04": "Before, the laboratory was the brand’s strongest advantage and existed only inside the company — in test reports no buyer would ever read.",
    "sm.s8.05": "Now it has a public page, a vocabulary and a guide. Every property the brand claims for a fabric can point to a test, and every test to a plain-language explanation. That is what the brand needed to position its fabrics on measured data rather than adjectives.",
    "sm.s8.06": "Before",
    "sm.s8.07": "Test reports",
    "sm.s8.08": "Internal only",
    "sm.s8.09": "Lab language",
    "sm.s8.10": "After",
    "sm.s8.11": "Public page",
    "sm.s8.12": "4 properties, 8 parameters explained",
    "sm.s8.13": "20-page guide",
    "sm.s8.14": "What I’d do next",
    "sm.s8.15": "Thresholds for every scale.",
    "sm.s8.16": "The page answers “is 4 out of 5 good?” but not “are 30,000 Martindale cycles good?” The next step is reference ranges: household use vs. heavy use.",
    "sm.s8.17": "Show a real test report.",
    "sm.s8.18": "The page names the test report as proof but never shows one. A single redacted example would do more than the four-step diagram.",
    "sm.s8.19": "Close the loop with product pages.",
    "sm.s8.20": "Each parameter in a fabric’s specifications should link to its explanation here. The page is a dictionary; product pages are where people need it.",
    "sm.meta.desc": "A landing page that turned an in-house testing lab into a selling point. Research, information architecture, UX writing and wireframes by Dmitrii Andreenko.",
  };

  const RU = {
    "sm.doc.title": "Лаборатория Souz-M — UX-кейс — Дмитрий Андреенко",
    "sm.back": "Все работы",
    "sm.k.role": "Роль",
    "sm.k.team": "Команда",
    "sm.k.year": "Год",
    "sm.k.live": "Ссылка",
    "sm.next": "Следующий кейс — Chistetika Lab",
    "sm.head.01": "UX-кейс · 2025",
    "sm.head.02": "Лаборатория Souz-M",
    "sm.head.03": "Как сделать скрытую лабораторию аргументом для покупателя",
    "sm.head.04": "Ведущий редактор — исследование, информационная архитектура, UX-тексты, вайрфреймы",
    "sm.head.05": "Shulman_prod (креативное руководство, визуальный дизайн)",
    "sm.head.06": "2025",
    "sm.s1.01": "Задача",
    "sm.s1.02": "Запрос звучал так: нужна страница, чтобы разместить PDF.",
    "sm.s1.03": "Souz-M продаёт мебельные ткани. Каждая ткань Souz-M и дочернего бренда Chistetika проходит испытания в собственной аккредитованной лаборатории компании. Характеристики в карточках товаров не переписаны у поставщиков — они измерены.",
    "sm.s1.04": "Это одно из самых сильных конкурентных преимуществ бренда, и о нём нигде не говорилось.",
    "sm.s1.05": "Нужен был лендинг для нового гайда по лабораторным испытаниям. Я предложил страницу, которая продаёт саму лабораторию, а гайд даёт ей глубину.",
    "sm.s1.06": "Выпущенная страница лаборатории Souz-M: первый экран с видео испытательного прибора и кнопкой «Скачать полный гайд (PDF)»",
    "sm.s1.07": "Страница",
    "sm.s1.08": "Лаборатория, о которой большинство покупателей не знали",
    "sm.s2.01": "Проблема",
    "sm.s2.02": "Доказательства говорили языком лаборатории.",
    "sm.s2.03": "«Тест Мартиндейла» мало что скажет человеку, который выбирает ткань для мебели.",
    "sm.s2.04": "Цифры без интерпретации бесполезны.",
    "sm.s2.05": "30 000 циклов — это много или мало? Без точки отсчёта число ничего не доказывает.",
    "sm.s2.06": "Лаборатория — это процесс, а не товар.",
    "sm.s2.07": "Её не положишь в корзину. Странице нужно было сделать невидимую работу видимой.",
    "sm.s2.08": "Что измеряет лаборатория",
    "sm.s2.09": "Тест Мартиндейла — <span class=\"dg__fig\">30 000</span> циклов",
    "sm.s2.10": "О чём спрашивает покупатель",
    "sm.s2.11": "Не протрётся ли обивка на диване?",
    "sm.s2.12": "Что должна сделать страница",
    "sm.s2.13": "Связать одно с другим.",
    "sm.s3.01": "Исходные данные",
    "sm.s3.02": "На входе было техническое описание испытаний: методики, стандарты, единицы измерения. Я переписал его в гайд для читателя без специальной подготовки, а Shulman_prod сделали из него PDF на 20 страниц.",
    "sm.s3.03": "Первая версия страницы просто перенесла этот текст в шаблон сайта: заголовок, определение и список из семи параметров.",
    "sm.s3.04": "Всё было верно. И ничего не работало.",
    "sm.s3.05": "Список отвечал на вопрос, которого посетитель не задавал.",
    "sm.s3.06": "<strong>Для кого страница.</strong> Для тех, кто выбирает ткань для мебели. Моя рабочая гипотеза: никто из них не спрашивает про испытания. Их интересует, будет ли ткань держать форму, не выгорит ли, не протрётся ли. Это так и осталось гипотезой — и на ней построена структура.",
    "sm.s3.07": "Гайд — страница 3 из 20",
    "sm.s3.08": "Разворот 3 из 20 в гайде: «Что такое лабораторные испытания?», иконки свойств и фотография испытательного прибора",
    "sm.s3.09": "v0 — тот же текст в шаблоне сайта",
    "sm.s3.10": "Первая версия страницы: слайдер с рулонами ткани, вопрос «Что такое лабораторные испытания?» и семь параметров списком прописными буквами; пустое место между двумя частями вырезано",
    "sm.s3.11": "v0",
    "sm.s3.12": "Верно, но бесполезно",
    "sm.s4.01": "Структура",
    "sm.s4.02": "Страница не заменяет гайд. Она его продаёт.",
    "sm.s4.03": "Каждый блок отвечает на один вопрос.",
    "sm.s4.04": "Шесть блоков страницы и вопрос, на который отвечает каждый",
    "sm.s4.05": "Первый экран",
    "sm.s4.06": "Что это? (и сразу — ссылка на гайд)",
    "sm.s4.07": "Из чего складывается качество",
    "sm.s4.08": "Что вы проверяете и почему мне это важно?",
    "sm.s4.09": "Как проходят испытания",
    "sm.s4.10": "Это правда или маркетинг?",
    "sm.s4.11": "Испытания на видео",
    "sm.s4.12": "Покажите.",
    "sm.s4.13": "Параметры и их интерпретация",
    "sm.s4.14": "Как читать цифры в карточке ткани?",
    "sm.s4.15": "Гайд",
    "sm.s4.16": "Где узнать подробности?",
    "sm.s4.17": "Выделены блоки, порядок которых и был решением: сначала свойства, потом доказательства, потом параметры.",
    "sm.s4.18": "Гайд предлагается дважды: на первом экране — для тех, кто пришёл за ним, и в конце — для тех, кого убедила страница. Каждый параметр заканчивается ссылкой на гайд. Страница работает как оглавление к PDF.",
    "sm.s4.19": "Первый экран",
    "sm.s4.20": "Скачать",
    "sm.s4.21": "Из чего складывается качество",
    "sm.s4.22": "Как проходят испытания",
    "sm.s4.23": "Испытания на видео",
    "sm.s4.24": "Параметры и их интерпретация",
    "sm.s4.25": "Подробнее в гайде ×8",
    "sm.s4.26": "Гайд",
    "sm.s4.27": "Скачать",
    "sm.s4.28": "Гайд · 20 страниц",
    "sm.s4.29": "Оглавление",
    "sm.s4.30": "Два входа, восемь переходов",
    "sm.s4.31": "Как складывалась структура",
    "sm.s4.32": "v0",
    "sm.s4.33": "Макет v0 целиком",
    "sm.s4.34": "Содержание гайда в шаблоне сайта",
    "sm.s4.35": "v1",
    "sm.s4.36": "Макет v1 целиком",
    "sm.s4.37": "Свойства на первом экране; первая карточка параметра из двух частей",
    "sm.s4.38": "v2",
    "sm.s4.39": "Макет v2 целиком — версия, которую я передал в работу",
    "sm.s4.40": "Свойства вынесены с первого экрана в отдельный блок: у первого экрана должна быть одна задача. Эту версию я передал в работу",
    "sm.s4.41": "v3",
    "sm.s4.42": "Макет v3 целиком",
    "sm.s4.43": "Серые вайрфреймы на сетке бренда",
    "sm.s4.44": "v4",
    "sm.s4.45": "Макет v4 целиком",
    "sm.s4.46": "Настоящие фотографии из лаборатории",
    "sm.s4.47": "Релиз",
    "sm.s4.48": "Выпущенная страница целиком",
    "sm.s4.49": "Визуальный дизайн — Shulman_prod",
    "sm.s4.50": "Шесть версий — от шаблона до релиза.",
    "sm.s5.01": "Решения",
    "sm.s5.02": "Свойства вместо параметров",
    "sm.s5.03": "Лаборатория измеряет восемь параметров. Покупатели спрашивают о четырёх свойствах: плотности, прочности, цветоустойчивости и износостойкости.",
    "sm.s5.04": "Я сгруппировал параметры по этим свойствам и сделал свойства вкладками.",
    "sm.s5.05": "Как спрашивает покупатель",
    "sm.s5.06": "Что измеряет лаборатория",
    "sm.s5.07": "Плотность",
    "sm.s5.08": "Поверхностная плотность",
    "sm.s5.09": "Толщина",
    "sm.s5.10": "Прочность",
    "sm.s5.11": "Разрывная нагрузка",
    "sm.s5.12": "Удлинение при разрыве",
    "sm.s5.13": "Цветоустойчивость",
    "sm.s5.14": "Устойчивость окраски к свету",
    "sm.s5.15": "Износостойкость",
    "sm.s5.16": "Устойчивость к пиллингу",
    "sm.s5.17": "Тест Мартиндейла",
    "sm.s5.18": "Устойчивость к изгибу",
    "sm.s5.19": "искусственная кожа",
    "sm.s5.20": "Перевод",
    "sm.s5.21": "Четыре вопроса, восемь ответов",
    "sm.s5.22": "Группы следуют вопросу покупателя, а не классификации лаборатории. Поэтому в одной вкладке три параметра, а в другой — один. Устойчивость к многократному изгибу относится к искусственной коже, а не к ткани, поэтому она стоит там, где её будет искать покупатель, — в износостойкости.",
    "sm.s5.23": "Посетитель входит через знакомое слово и уходит с техническим термином, который теперь узнает в карточке товара. На этом переводе держится вся остальная страница.",
    "sm.s5.24": "Два вопроса к каждому параметру",
    "sm.s5.25": "Каждый параметр отвечает на два вопроса. Первый: что это и как это измеряют? Второй: что это значит для мебели?",
    "sm.s5.26": "Цифра становится аргументом, только когда рядом сказано, что из неё следует.",
    "sm.s5.27": "<span class=\"dg__fig\">Параметр 3</span> Разрывная нагрузка",
    "sm.s5.28": "Что это",
    "sm.s5.29": "Максимальное усилие, которое ткань выдерживает при растяжении до разрыва. Измеряется в ньютонах <span class=\"dg__fig\">(Н)</span>.",
    "sm.s5.30": "Что это значит",
    "sm.s5.31": "Чем выше разрывная нагрузка, тем прочнее ткань: она лучше выдерживает натяжение, реже деформируется и дольше сохраняет швы.",
    "sm.s5.32": "Подробнее в гайде",
    "sm.s5.33": "Анатомия",
    "sm.s5.34": "Слева — определение, справа — следствие",
    "sm.s5.35": "Я проверил три раскладки карточки: вертикальную, с визуализацией и в две колонки. В финальном дизайне Shulman_prod превратили две половины в раскрывающийся аккордеон, чтобы восемь параметров не слились в стену текста.",
    "sm.s5.36": "v1 — вертикальная",
    "sm.s5.37": "Вариант карточки v1: вертикальная синяя карточка «Поверхностная плотность» с плашками свойств",
    "sm.s5.38": "v2 — с визуализацией",
    "sm.s5.39": "Вариант карточки v2: карточка с зелёной визуализацией поверхности ткани",
    "sm.s5.40": "v3 — в две колонки",
    "sm.s5.41": "Вариант карточки v3: карточка в две колонки — серая шапка и синяя половина с интерпретацией",
    "sm.s5.42": "Тёмный блок «Параметры и их интерпретация» на выпущенной странице, первый пункт раскрыт",
    "sm.s5.43": "Релиз",
    "sm.s5.44": "Аккордеон в дизайне Shulman_prod",
    "sm.s5.45": "Процесс как доказательство",
    "sm.s5.46": "Четыре шага — подготовка, тестирование, документация, выход на рынок — нужны не для того, чтобы объяснить процесс. Они доказывают, что за словом «проверено» стоит протокол испытаний.",
    "sm.s5.47": "Поэтому протокол назван уже в первом абзаце страницы.",
    "sm.s5.48": "Полоса из четырёх шагов на выпущенной странице: подготовка, тестирование, создание документации, выход на рынок",
    "sm.s5.49": "доказательство",
    "sm.s5.50": "Доказательство",
    "sm.s5.51": "Главный аргумент — на третьем шаге",
    "sm.s6.01": "Язык",
    "sm.s6.02": "Технический материал нужно было переписать, не потеряв точности.",
    "sm.s6.03": "«Пиллинг» остался, но с понятным пояснением: катышки из скатанных волокон.",
    "sm.s6.04": "У пятибалльных шкал появился порог, чтобы оценка что-то значила:",
    "sm.s6.05": "Оценка ниже 4 баллов означает, что материал будет быстро терять цвет.",
    "sm.s6.06": "Задача была не убрать терминологию, а сделать каждый термин понятным.",
    "sm.s6.07": "v0 · шаблон",
    "sm.s6.08": "УСТОЙЧИВОСТЬ К ОБРАЗОВАНИЮ ВОРСИСТОСТИ И ПИЛЛИНГА",
    "sm.s6.09": "Релиз · Параметр 6",
    "sm.s6.10": "Способность ткани сохранять гладкую поверхность и сопротивляться образованию катышков (скатанных волокон) при эксплуатации. Оценивается по пятибалльной шкале. Оценка ниже 4 баллов указывает на склонность материала к пиллингу.",
    "sm.s6.11": "До / после",
    "sm.s6.12": "Тот же факт — для другого читателя",
    "sm.s6.13": "Ниже 4 — быстро выцветает.",
    "sm.s7.01": "После передачи",
    "sm.s7.02": "Визуальный дизайн делал не я. Структура, порядок блоков и тексты ушли в разработку без изменений.",
    "sm.s7.03": "Shulman_prod добавили визуальный слой, для которого структура оставляла место: фотографии из лаборатории во вкладках, иконки процесса и тёмный блок параметров на фоне интерьера. Последний ход возвращает разговор из лаборатории в комнату — от того, как ткань испытывают, к тому, зачем это нужно.",
    "sm.s7.04": "v2 — версия, которую я передал",
    "sm.s7.05": "Прототип v2 целиком — версия, переданная дизайн-студии",
    "sm.s7.06": "Релиз — souz-m.ru/laboratoriya",
    "sm.s7.07": "Выпущенная страница целиком, сверху донизу",
    "sm.s7.08": "Структура та же, добавился визуальный слой.",
    "sm.s8.01": "Результат",
    "sm.s8.02": "Страница опубликована на souz-m.ru/laboratoriya, ссылки на неё есть в меню и футере сайта.",
    "sm.s8.03": "Доступа к аналитике страницы у меня нет, поэтому цифр здесь не будет. Показать я могу тот результат, ради которого писался бриф.",
    "sm.s8.04": "Раньше лаборатория была самым сильным преимуществом бренда и существовала только внутри компании — в протоколах, которые не прочитает ни один покупатель.",
    "sm.s8.05": "Теперь у неё есть публичная страница, словарь и гайд. За каждым свойством, которое бренд заявляет для ткани, стоит испытание, а за каждым испытанием — объяснение простым языком. Именно это было нужно бренду, чтобы продавать ткани, опираясь на измерения, а не на эпитеты.",
    "sm.s8.06": "До",
    "sm.s8.07": "Протоколы испытаний",
    "sm.s8.08": "Только внутри компании",
    "sm.s8.09": "Язык лаборатории",
    "sm.s8.10": "После",
    "sm.s8.11": "Публичная страница",
    "sm.s8.12": "4 свойства и 8 параметров с объяснениями",
    "sm.s8.13": "Гайд на 20 страниц",
    "sm.s8.14": "Что бы я сделал дальше",
    "sm.s8.15": "Пороги для каждой шкалы.",
    "sm.s8.16": "Страница отвечает на вопрос «4 из 5 — это хорошо?», но не на вопрос «30 000 циклов Мартиндейла — это хорошо?». Следующий шаг — ориентиры: для домашнего использования и для интенсивной нагрузки.",
    "sm.s8.17": "Показать настоящий протокол.",
    "sm.s8.18": "Страница называет протокол доказательством, но ни разу его не показывает. Один пример со скрытыми данными убедил бы сильнее, чем схема из четырёх шагов.",
    "sm.s8.19": "Связать страницу с карточками товаров.",
    "sm.s8.20": "Каждый параметр в характеристиках ткани должен вести к своему объяснению здесь. Страница — это словарь, а нужен он там, где человек выбирает ткань, — в карточке товара.",
    "sm.meta.desc": "Лендинг, который превратил внутреннюю испытательную лабораторию в аргумент для покупателя. Исследование, информационная архитектура, UX-тексты и вайрфреймы — Дмитрий Андреенко.",
  };

  window.I18N = window.I18N || { en: {}, ru: {} };
  Object.assign(window.I18N.en, EN);
  Object.assign(window.I18N.ru, RU);
})();
